
package adapters

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	statesync "github.com/pragmataW/tddmaster/internal/sync"
	"github.com/pragmataW/tddmaster/internal/sync/adapters/shared"
	"github.com/pragmataW/tddmaster/internal/state"
)

// =============================================================================
// File Paths
// =============================================================================

const opencodePluginsDir = ".opencode/plugins"
const opencodeAgentsDir = ".opencode/agents"
const opencodeSkillsDir = ".opencode/skills"
const opencodeConfigFile = "opencode.json"

// =============================================================================
// OpenCodeAdapter
// =============================================================================

// OpenCodeAdapter implements ToolAdapter for OpenCode.
type OpenCodeAdapter struct{}

func (a *OpenCodeAdapter) ID() state.CodingToolId {
	return state.CodingToolOpencode
}

func (a *OpenCodeAdapter) Capabilities() statesync.ToolCapabilities {
	return statesync.ToolCapabilities{
		Rules:  true,
		Hooks:  true,
		Agents: true,
		Specs:  true,
		Mcp:    true,
		Interaction: statesync.InteractionHints{
			HasAskUserTool:        false,
			OptionPresentation:    "prose",
			HasSubAgentDelegation: true,
			SubAgentMethod:        "delegation",
		},
	}
}

func (a *OpenCodeAdapter) SyncRules(ctx statesync.SyncContext, options *statesync.SyncOptions) error {
	return shared.SyncAgentsMd(ctx, options)
}

func (a *OpenCodeAdapter) SyncHooks(ctx statesync.SyncContext, _ *statesync.SyncOptions) error {
	pluginsDir := filepath.Join(ctx.Root, opencodePluginsDir)
	if err := os.MkdirAll(pluginsDir, 0o755); err != nil {
		return err
	}

	return os.WriteFile(
		filepath.Join(pluginsDir, "tddmaster.ts"),
		[]byte(buildOpenCodePluginContent(ctx.CommandPrefix)),
		0o644,
	)
}

func (a *OpenCodeAdapter) SyncAgents(ctx statesync.SyncContext, _ *statesync.SyncOptions) error {
	agentsDir := filepath.Join(ctx.Root, opencodeAgentsDir)
	if err := os.MkdirAll(agentsDir, 0o755); err != nil {
		return err
	}

	if err := os.WriteFile(filepath.Join(agentsDir, "tddmaster-executor.md"), []byte(buildOpenCodeExecutorAgentMd(ctx.CommandPrefix, ctx.Manifest)), 0o644); err != nil {
		return err
	}

	if err := os.WriteFile(filepath.Join(agentsDir, "tddmaster-verifier.md"), []byte(buildOpenCodeVerifierAgentMd(ctx.Manifest)), 0o644); err != nil {
		return err
	}

	if ctx.Manifest != nil && ctx.Manifest.TddMode {
		return os.WriteFile(filepath.Join(agentsDir, "test-writer.md"), []byte(buildOpenCodeTestWriterAgentMd()), 0o644)
	}
	return nil
}

func (a *OpenCodeAdapter) SyncSpecs(ctx statesync.SyncContext, specPath string) error {
	data, err := os.ReadFile(specPath)
	if err != nil {
		return nil // skip gracefully
	}

	content := strings.TrimSpace(string(data))
	if content == "" {
		return nil
	}

	segments := strings.Split(specPath, "/")
	specName := "unknown"
	if len(segments) >= 2 {
		specName = segments[len(segments)-2]
	}

	parsed := parseOpenCodeSpecMd(content)

	skillsDir := filepath.Join(ctx.Root, opencodeSkillsDir)
	if err := os.MkdirAll(skillsDir, 0o755); err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(skillsDir, specName+".md"), []byte(buildOpenCodeSkillMd(parsed)), 0o644)
}

func (a *OpenCodeAdapter) SyncMcp(ctx statesync.SyncContext) error {
	configPath := filepath.Join(ctx.Root, opencodeConfigFile)

	existing := map[string]interface{}{}
	if data, err := os.ReadFile(configPath); err == nil {
		_ = json.Unmarshal(data, &existing)
	}

	parts := strings.Fields(ctx.CommandPrefix)
	command := "npx"
	if len(parts) > 0 {
		command = parts[0]
	}
	args := append(parts[1:], "mcp-serve") //nolint:gocritic

	existingMcp, _ := existing["mcp"].(map[string]interface{})
	if existingMcp == nil {
		existingMcp = map[string]interface{}{}
	}
	existingMcp["tddmaster"] = map[string]interface{}{
		"type":    "local",
		"command": command,
		"args":    args,
	}
	existing["mcp"] = existingMcp

	data, err := json.MarshalIndent(existing, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')

	return os.WriteFile(configPath, data, 0o644)
}

// =============================================================================
// Content generators
// =============================================================================

func buildOpenCodePluginContent(commandPrefix string) string {
	lines := []string{
		"// Generated by tddmaster — do not edit manually",
		`import { execSync } from "node:child_process";`,
		"",
		"const run = (event: string): void => {",
		"  try {",
		"    execSync(`" + commandPrefix + " invoke-hook ${event}`, {",
		`      stdio: "inherit",`,
		"      timeout: 10000,",
		"    });",
		"  } catch {",
		"    // Hook failure should not block the session",
		"  }",
		"};",
		"",
		"export default async () => ({",
		`  "session.created": async () => {`,
		`    run("session-start");`,
		"  },",
		`  "tool.execute.before": async (params: { toolName: string }) => {`,
		`    if (["write", "shell"].includes(params.toolName)) {`,
		`      run("pre-tool-use");`,
		"    }",
		"  },",
		`  "tool.execute.after": async (params: { toolName: string }) => {`,
		`    if (params.toolName === "write") {`,
		`      run("post-file-write");`,
		`    } else if (params.toolName === "shell") {`,
		`      run("post-bash");`,
		"    }",
		"  },",
		`  "session.deleted": async () => {`,
		`    run("stop");`,
		"  },",
		"});",
		"",
	}

	return strings.Join(lines, "\n")
}

func buildOpenCodeExecutorAgentMd(commandPrefix string, manifest *state.Manifest) string {
	lines := []string{
		"---",
		"name: tddmaster-executor",
		`description: "Executes a single tddmaster task. Follows spec behavioral rules and reports structured results."`,
		"tools: read, write, glob, grep, shell, delegate",
		"---",
		"",
		"You are executing a single task from a tddmaster spec.",
		"Your ONLY job is to complete the task described in the prompt.",
		"Follow all behavioral rules provided in the prompt.",
		"Do NOT start new tasks, explore unrelated code, or make architectural decisions.",
		"If the task is too vague to execute, say so immediately.",
		"",
		"## TDD Context",
		"If `tddPhase` is present in your task context, follow RGR discipline:",
		"- `red` — write failing tests ONLY; do NOT write implementation code",
		"- `green` — implement minimum code to make failing tests pass",
		"- `refactor` — improve structure without changing behavior; tests must still pass",
		"If `tddFailureReport` is present, read `failedACs` and address them before anything else.",
		"Include `tddPhase` in your JSON report when it is set.",
		"",
		"## Refactor Mode",
		"If `refactorInstructions` is present in your task context, this is a REFACTOR round:",
		"1. Apply each note in `refactorInstructions.notes` verbatim.",
		"2. Do NOT change test behavior — the full test suite must still pass.",
		"3. Report `refactorApplied: true` in your JSON output.",
		"The verifier will re-run tests after your changes to confirm behavior is preserved.",
		"",
		"## Reporting",
		"When finished, provide a structured JSON summary:",
		"```json",
		`{"completed": ["<item IDs done>"], "remaining": ["<item IDs not done>"], "blocked": ["<item IDs needing decisions>"], "filesModified": ["<paths>"], "tddPhase": "<phase or omit>", "refactorApplied": true|false}`,
		"```",
		"The orchestrator will submit this to `" + commandPrefix + " next --answer` on your behalf.",
		"",
	}

	return strings.Join(lines, "\n")
}

func buildOpenCodeVerifierAgentMd(manifest *state.Manifest) string {
	typeCheckCmd, testCmd := resolveVerifierCommands(manifest)

	// TDD mode guard: only inject RED/GREEN/REFACTOR phase blocks when TDD is enabled.
	// Non-TDD projects must use VerifierInstructions — sending TDD phase blocks to a
	// non-TDD verifier causes confusion and incorrect phase-specific behavior.
	tddMode := manifest != nil && manifest.TddMode
	var verifierInstructions string
	if tddMode {
		verifierInstructions = shared.VerifierInstructionsAllPhases(typeCheckCmd, testCmd)
	} else {
		verifierInstructions = shared.VerifierInstructions(typeCheckCmd, testCmd)
	}

	lines := []string{
		"---",
		"name: tddmaster-verifier",
		`description: "Independently verifies completed task work. Read-only. Never sees the executor's context."`,
		"tools: read, glob, grep, shell",
		"---",
		"",
		verifierInstructions,
		"",
		"The orchestrator will use this report for the tddmaster status report.",
		"",
	}

	return strings.Join(lines, "\n")
}

func buildOpenCodeTestWriterAgentMd() string {
	lines := []string{
		"---",
		"name: test-writer",
		`description: "Writes tests FIRST following TDD principles. Reads the project rule set from .opencode/skills/ and AGENTS.md before writing any test."`,
		"tools: read, write, glob, grep, shell",
		"---",
		"",
		shared.TestWriterInstructions("`.opencode/skills/` and `AGENTS.md`"),
		"",
	}

	return strings.Join(lines, "\n")
}

type opencodeSpecParsed struct {
	title            string
	concerns         string
	discoveryAnswers string
	contributorGuide string
	publicAPI        string
	outOfScope       string
	tasks            string
	verification     string
}

var opencodeH1Re = regexp.MustCompile(`(?m)^# Spec:\s*(.+)$`)

func parseOpenCodeSpecMd(content string) opencodeSpecParsed {
	var parsed opencodeSpecParsed

	if m := opencodeH1Re.FindStringSubmatch(content); m != nil {
		parsed.title = strings.TrimSpace(m[1])
	} else {
		parsed.title = "Untitled"
	}

	sections := map[string]string{}
	parts := strings.Split(content, "\n## ")
	for _, part := range parts {
		newlineIdx := strings.IndexByte(part, '\n')
		if newlineIdx == -1 {
			continue
		}
		heading := strings.ToLower(strings.TrimSpace(part[:newlineIdx]))
		body := strings.TrimSpace(part[newlineIdx+1:])
		sections[heading] = body
	}

	findSection := func(prefix string) string {
		for k, v := range sections {
			if strings.HasPrefix(k, strings.ToLower(prefix)) {
				return v
			}
		}
		return ""
	}

	parsed.concerns = findSection("concerns")
	parsed.discoveryAnswers = findSection("discovery answers")
	parsed.contributorGuide = findSection("contributor guide")
	parsed.publicAPI = findSection("public api")
	parsed.outOfScope = findSection("out of scope")
	parsed.tasks = findSection("tasks")
	parsed.verification = findSection("verification")

	return parsed
}

func buildOpenCodeSkillMd(spec opencodeSpecParsed) string {
	lines := []string{
		"---",
		"name: " + spec.title,
		`description: "tddmaster spec: ` + spec.title + `"`,
		"---",
		"",
		"# " + spec.title,
		"",
	}

	if spec.discoveryAnswers != "" {
		lines = append(lines, "## Overview", "", spec.discoveryAnswers, "")
	}
	if spec.concerns != "" {
		lines = append(lines, "## Concerns", "", spec.concerns, "")
	}
	if spec.contributorGuide != "" {
		lines = append(lines, "## Contributor Guide", "", spec.contributorGuide, "")
	}
	if spec.publicAPI != "" {
		lines = append(lines, "## Public API", "", spec.publicAPI, "")
	}
	if spec.outOfScope != "" {
		lines = append(lines, "## Out of Scope", "", spec.outOfScope, "")
	}
	if spec.tasks != "" {
		lines = append(lines, "## Tasks", "", spec.tasks, "")
	}
	if spec.verification != "" {
		lines = append(lines, "## Verification", "", spec.verification, "")
	}

	return strings.Join(lines, "\n")
}
