package adapters

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/pragmataW/tddmaster/internal/state"
	statesync "github.com/pragmataW/tddmaster/internal/sync"
	"github.com/pragmataW/tddmaster/internal/sync/adapters/shared"
)

// =============================================================================
// File Paths
// =============================================================================

const opencodePluginsDir = ".opencode/plugins"
const opencodeAgentsDir = ".opencode/agents"
const opencodeSkillsDir = ".opencode/skills"

// =============================================================================
// OpenCodeAdapter
// =============================================================================

// OpenCodeAdapter implements ToolAdapter for OpenCode.
type OpenCodeAdapter struct{}

func (a *OpenCodeAdapter) ID() state.CodingToolId {
	return state.CodingToolOpencode
}

func (a *OpenCodeAdapter) Capabilities() statesync.ToolCapabilities {
	return statesync.ToolCapabilities{
		Rules:  true,
		Hooks:  true,
		Agents: true,
		Specs:  true,
		Mcp:    false,
		Interaction: statesync.InteractionHints{
			HasAskUserTool:        false,
			OptionPresentation:    "prose",
			HasSubAgentDelegation: true,
			SubAgentMethod:        "delegation",
			AskUserStrategy:       "tddmaster_block",
		},
	}
}

func (a *OpenCodeAdapter) SyncRules(ctx statesync.SyncContext, options *statesync.SyncOptions) error {
	return shared.SyncAgentsMd(ctx, options)
}

func (a *OpenCodeAdapter) SyncHooks(ctx statesync.SyncContext, _ *statesync.SyncOptions) error {
	pluginsDir := filepath.Join(ctx.Root, opencodePluginsDir)
	if err := os.MkdirAll(pluginsDir, 0o755); err != nil {
		return err
	}

	return os.WriteFile(
		filepath.Join(pluginsDir, "tddmaster.ts"),
		[]byte(buildOpenCodePluginContent(ctx.CommandPrefix)),
		0o644,
	)
}

func (a *OpenCodeAdapter) SyncAgents(ctx statesync.SyncContext, _ *statesync.SyncOptions) error {
	agentsDir := filepath.Join(ctx.Root, opencodeAgentsDir)
	if err := os.MkdirAll(agentsDir, 0o755); err != nil {
		return err
	}

	if err := os.WriteFile(filepath.Join(agentsDir, "tddmaster-executor.md"), []byte(buildOpenCodeExecutorAgentMd(ctx.Root, ctx.CommandPrefix, ctx.Rules, ctx.Manifest)), 0o644); err != nil {
		return err
	}

	if err := os.WriteFile(filepath.Join(agentsDir, "tddmaster-verifier.md"), []byte(buildOpenCodeVerifierAgentMd(ctx.Root, ctx.Rules, ctx.Manifest)), 0o644); err != nil {
		return err
	}

	if ctx.Manifest != nil && ctx.Manifest.TddMode {
		return os.WriteFile(filepath.Join(agentsDir, "test-writer.md"), []byte(buildOpenCodeTestWriterAgentMd(ctx.Root, ctx.Rules, ctx.Manifest)), 0o644)
	}
	return nil
}

func (a *OpenCodeAdapter) SyncSpecs(ctx statesync.SyncContext, specPath string) error {
	data, err := os.ReadFile(specPath)
	if err != nil {
		return nil // skip gracefully
	}

	content := strings.TrimSpace(string(data))
	if content == "" {
		return nil
	}

	segments := strings.Split(specPath, "/")
	specName := "unknown"
	if len(segments) >= 2 {
		specName = segments[len(segments)-2]
	}

	parsed := parseOpenCodeSpecMd(content)

	skillsDir := filepath.Join(ctx.Root, opencodeSkillsDir)
	if err := os.MkdirAll(skillsDir, 0o755); err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(skillsDir, specName+".md"), []byte(buildOpenCodeSkillMd(parsed)), 0o644)
}

func (a *OpenCodeAdapter) SyncMcp(statesync.SyncContext) error {
	return nil // not supported
}

// =============================================================================
// Content generators
// =============================================================================

func buildOpenCodePluginContent(commandPrefix string) string {
	lines := []string{
		"// Generated by tddmaster — do not edit manually",
		`import { execSync } from "node:child_process";`,
		"",
		"const run = (event: string): void => {",
		"  try {",
		"    execSync(`" + commandPrefix + " invoke-hook ${event}`, {",
		`      stdio: "inherit",`,
		"      timeout: 10000,",
		"    });",
		"  } catch {",
		"    // Hook failure should not block the session",
		"  }",
		"};",
		"",
		"export default async () => ({",
		`  "session.created": async () => {`,
		`    run("session-start");`,
		"  },",
		`  "tool.execute.before": async (params: { toolName: string }) => {`,
		`    if (["write", "shell"].includes(params.toolName)) {`,
		`      run("pre-tool-use");`,
		"    }",
		"  },",
		`  "tool.execute.after": async (params: { toolName: string }) => {`,
		`    if (params.toolName === "write") {`,
		`      run("post-file-write");`,
		`    } else if (params.toolName === "shell") {`,
		`      run("post-bash");`,
		"    }",
		"  },",
		`  "session.deleted": async () => {`,
		`    run("stop");`,
		"  },",
		"});",
		"",
	}

	return strings.Join(lines, "\n")
}

func buildOpenCodeToolsBlock(tools ...string) []string {
	lines := []string{"tools:"}
	for _, tool := range tools {
		lines = append(lines, "  "+tool+": true")
	}
	return lines
}

func buildOpenCodeAgentMd(name, description string, tools []string, body ...string) string {
	lines := []string{
		"---",
		"name: " + name,
		description,
	}
	lines = append(lines, buildOpenCodeToolsBlock(tools...)...)
	lines = append(lines, "---", "")
	lines = append(lines, body...)
	lines = append(lines, "")
	return strings.Join(lines, "\n")
}

func openCodeConventionSources() shared.ConventionSources {
	return shared.ConventionSources{
		ProjectFile: "AGENTS.md",
		HomeFile:    "~/.config/opencode/AGENTS.md",
	}
}

func buildOpenCodeExecutorAgentMd(root, commandPrefix string, rules []string, manifest *state.Manifest) string {
	preamble := shared.ConventionsPreamble(root, openCodeConventionSources(), rules, manifest.ShouldInjectConventions())
	return buildOpenCodeAgentMd(
		"tddmaster-executor",
		`description: "Executes a single tddmaster task. Follows spec behavioral rules and reports structured results."`,
		[]string{"read", "write", "glob", "grep", "shell", "delegate"},
		preamble+shared.ExecutorInstructions(commandPrefix),
	)
}

func buildOpenCodeVerifierAgentMd(root string, rules []string, manifest *state.Manifest) string {
	typeCheckCmd, testCmd := resolveVerifierCommands(manifest)

	tddMode := manifest != nil && manifest.TddMode
	skipVerify := manifest != nil && manifest.SkipVerify
	var verifierInstructions string
	if tddMode {
		verifierInstructions = shared.VerifierInstructionsAllPhases(typeCheckCmd, testCmd, skipVerify)
	} else {
		verifierInstructions = shared.VerifierInstructions(typeCheckCmd, testCmd)
	}

	preamble := shared.ConventionsPreamble(root, openCodeConventionSources(), rules, manifest.ShouldInjectConventions())

	return buildOpenCodeAgentMd(
		"tddmaster-verifier",
		`description: "Independently verifies completed task work. Read-only. Never sees the executor's context."`,
		[]string{"read", "glob", "grep", "shell"},
		preamble+verifierInstructions,
		"The orchestrator will use this report for the tddmaster status report.",
	)
}

func buildOpenCodeTestWriterAgentMd(root string, rules []string, manifest *state.Manifest) string {
	preamble := shared.ConventionsPreamble(root, openCodeConventionSources(), rules, manifest.ShouldInjectConventions())
	return buildOpenCodeAgentMd(
		"test-writer",
		`description: "Writes tests FIRST following TDD principles. Reads the project rule set from .opencode/skills/ and AGENTS.md before writing any test."`,
		[]string{"read", "write", "glob", "grep", "shell"},
		preamble+shared.TestWriterInstructions("`.opencode/skills/` and `AGENTS.md`"),
	)
}

type opencodeSpecParsed struct {
	title            string
	concerns         string
	discoveryAnswers string
	contributorGuide string
	publicAPI        string
	outOfScope       string
	tasks            string
	verification     string
}

var opencodeH1Re = regexp.MustCompile(`(?m)^# Spec:\s*(.+)$`)

func parseOpenCodeSpecMd(content string) opencodeSpecParsed {
	var parsed opencodeSpecParsed

	if m := opencodeH1Re.FindStringSubmatch(content); m != nil {
		parsed.title = strings.TrimSpace(m[1])
	} else {
		parsed.title = "Untitled"
	}

	sections := map[string]string{}
	parts := strings.Split(content, "\n## ")
	for _, part := range parts {
		newlineIdx := strings.IndexByte(part, '\n')
		if newlineIdx == -1 {
			continue
		}
		heading := strings.ToLower(strings.TrimSpace(part[:newlineIdx]))
		body := strings.TrimSpace(part[newlineIdx+1:])
		sections[heading] = body
	}

	findSection := func(prefix string) string {
		for k, v := range sections {
			if strings.HasPrefix(k, strings.ToLower(prefix)) {
				return v
			}
		}
		return ""
	}

	parsed.concerns = findSection("concerns")
	parsed.discoveryAnswers = findSection("discovery answers")
	parsed.contributorGuide = findSection("contributor guide")
	parsed.publicAPI = findSection("public api")
	parsed.outOfScope = findSection("out of scope")
	parsed.tasks = findSection("tasks")
	parsed.verification = findSection("verification")

	return parsed
}

func buildOpenCodeSkillMd(spec opencodeSpecParsed) string {
	lines := []string{
		"---",
		"name: " + spec.title,
		`description: "tddmaster spec: ` + spec.title + `"`,
		"---",
		"",
		"# " + spec.title,
		"",
	}

	if spec.discoveryAnswers != "" {
		lines = append(lines, "## Overview", "", spec.discoveryAnswers, "")
	}
	if spec.concerns != "" {
		lines = append(lines, "## Concerns", "", spec.concerns, "")
	}
	if spec.contributorGuide != "" {
		lines = append(lines, "## Contributor Guide", "", spec.contributorGuide, "")
	}
	if spec.publicAPI != "" {
		lines = append(lines, "## Public API", "", spec.publicAPI, "")
	}
	if spec.outOfScope != "" {
		lines = append(lines, "## Out of Scope", "", spec.outOfScope, "")
	}
	if spec.tasks != "" {
		lines = append(lines, "## Tasks", "", spec.tasks, "")
	}
	if spec.verification != "" {
		lines = append(lines, "## Verification", "", spec.verification, "")
	}

	return strings.Join(lines, "\n")
}
