// Package shared provides utilities shared by multiple tool adapters.
package shared

import (
	"os"
	"strings"

	statesync "github.com/pragmataW/tddmaster/internal/sync"
)

// =============================================================================
// Constants
// =============================================================================

const AgentsMDFile = "AGENTS.md"
const NosStart = "<!-- tddmaster:start -->"
const NosEnd = "<!-- tddmaster:end -->"

// =============================================================================
// Content generators
// =============================================================================

// BuildProtocol generates the tddmaster protocol section.
func BuildProtocol(commandPrefix string, options *statesync.SyncOptions) string {
	allowGit := false
	if options != nil {
		allowGit = options.AllowGit
	}

	lines := []string{
		"## tddmaster Protocol",
		"",
		"# Generated by tddmaster — do not edit manually",
		"",
		"### What is tddmaster",
		"",
		"This project uses tddmaster for state-driven orchestration.",
		"Do NOT read `.tddmaster/rules/`, `.tddmaster/specs/`, or concern files directly.",
		"tddmaster gives you exactly what you need via JSON output.",
		"",
		"### Protocol",
		"",
		"    " + commandPrefix + " spec <name> next                           # get current instruction",
		"    " + commandPrefix + ` spec <name> next --answer="your response"  # submit result and advance`,
		"",
		"Every tddmaster command that operates on a spec MUST include `spec <name>`.",
		"Never omit it. Use `" + commandPrefix + " spec list` to see available specs.",
		"",
		"### Task recovery vs spec termination",
		"",
		"These three commands look similar but have very different blast radii:",
		"",
		"- `" + commandPrefix + " undo` — resets the most recently completed task (task-level, reversible)",
		"- `" + commandPrefix + " spec <name> task undo <id>` — resets a specific task (task-level, reversible)",
		"- `" + commandPrefix + " spec <name> done` / `cancel` — terminates the ENTIRE spec and wipes the",
		"  execution context (spec-level, use `reopen --resume-execution` to recover execution state)",
		"",
		"If the user says \"undo that task\" or \"I didn't mean to mark that done\", use `undo` —",
		"never `done`/`cancel`. `undo` only flips the task flag; it does not rewind iteration",
		"counters or TDD phase state. Plain `reopen` is for discovery revision; `" + commandPrefix + " spec <name> reopen --resume-execution` is for accidental terminal completion.",
		"",
		"### Why tddmaster calls matter",
		"",
		"tddmaster is not a form to fill out. It is a live state machine that the user",
		"watches in real-time. Every `" + commandPrefix + " next --answer` call:",
		"",
		"- Updates the spec file on disk (the user sees it change)",
		"- Updates the terminal dashboard if `tddmaster watch` is running",
		"- Advances the state machine to the next phase",
		"- Records the decision permanently in the project history",
		"",
		"When you batch-submit answers or backfill discovery responses yourself,",
		"the user sees nothing happening — then suddenly everything jumps forward.",
		"This defeats the purpose.",
		"",
		"Call tddmaster ONCE per interaction. Ask the user ONE question. Wait for",
		"their answer. Submit it. Ask the next. The user is watching every step.",
		"Do NOT pre-fill answers. Do NOT batch multiple answers. Do NOT answer",
		"discovery questions yourself — the user's input is the data.",
		"",
		"### When to call tddmaster next",
		"",
		"You MUST call `" + commandPrefix + " next` in these situations:",
		"",
		"1. At the **START** of every conversation (first thing you do)",
		"2. **BEFORE** creating or modifying any file (to verify you have an active task)",
		"3. **AFTER** completing a logical unit of work (to report progress)",
		"4. When you encounter a **DECISION** that affects architecture or scope",
		"5. When you are **UNSURE** what to do next",
		"",
		"NEVER proceed with implementation without checking tddmaster first.",
		"NEVER make architectural decisions independently — tddmaster routes them to the user.",
		"",
		"### TDD Protocol",
		"",
		"When `TDDEnabled` is `true`, tddmaster enforces Red-Green-Refactor cycles.",
		"",
		"The executor JSON context includes:",
		"- `tddPhase`: current cycle phase — `\"red\"` | `\"green\"` | `\"refactor\"` | `\"\"`",
		"- `tddVerificationContext.instruction`: what the verifier expects for this phase",
		"- `tddFailureReport`: present when last verification failed — contains `reason`, `failedACs`, `retryCount`, `maxRetries`, `willBlock`",
		"",
		"**Phase rules:**",
		"- `red` — write failing tests ONLY; do NOT write implementation code",
		"- `green` — implement the minimum code to make failing tests pass",
		"- `refactor` — improve code structure; all tests must still pass; behavior must not change",
		"",
		"Include `tddPhase` in your status report when it is set.",
		"When `tddFailureReport` is present, address `failedACs` before reporting done.",
	}

	if !allowGit {
		lines = append(lines,
			"",
			"### Git is read-only",
			"",
			"You MUST NOT run git write commands: commit, add, push, checkout, stash,",
			"reset, merge, rebase, cherry-pick. The user controls git. You control files.",
			"You MAY read from git: log, diff, status, show, blame.",
		)
	}

	lines = append(lines,
		"",
		"### Interactive choices",
		"",
		"Present choices as numbered lists. Users select by number.",
		"When interactiveOptions are present in tddmaster output, present each as a",
		"numbered item with its label and description. Ask the user to pick a number.",
		"Use the `commandMap` to resolve the user's selection to a CLI command.",
		"",
		"### Decision principle: Explicit > Clever",
		"",
		"You NEVER skip steps, bypass questions, or make assumptions on behalf of the user.",
		"- Discovery questions → ask the user, don't answer yourself",
		"- Classification → ask the user, don't infer",
		"- Spec approval → ask the user, don't auto-approve",
		"- Task refinement → ask the user, don't self-assign",
		"- Rule promotion → ask the user, don't decide",
		`If you think something can be skipped, ASK "would you like to skip this?" — don't skip it.`,
		"NEVER suggest bypassing or skipping tddmaster. Discovery is not overhead.",
		"NEVER ask permission to run the next tddmaster command. After spec new → run next. After approve → run next. Just run it.",
		"",
		"### Command execution",
		"",
		"When told to run a tddmaster command, execute it IMMEDIATELY. Do not explore,",
		"research, read source code, or plan first. The command output contains all the",
		"context you need. Exploring tddmaster internals wastes tokens and delays the user.",
		"",
		"### JSON output",
		"",
		"tddmaster returns JSON with a `phase` field and phase-specific instructions.",
		"The `meta` block contains resume context - use it to orient yourself,",
		"especially after compaction or at the start of a new session.",
		"Follow the `instruction` field. Use `transition` commands to advance state.",
		"",
	)

	return strings.Join(lines, "\n")
}

// BuildCoaching generates the tddmaster coaching section.
func BuildCoaching(commandPrefix string) string {
	lines := []string{
		"### Convention discovery",
		"",
		"When you discover a pattern, receive a correction, or identify a recurring",
		`preference from the user, ask: "Should this be a permanent rule for this`,
		`project, or just for this task?" If permanent, run: ` + "`" + commandPrefix + " rule add",
		`"<description>"` + "`. If just this task, note it and move on.",
		"Never write to `.tddmaster/rules/` directly.",
		"",
		"### How to promote rules",
		"",
		"When a convention should be permanent, use the tddmaster CLI to register it:",
		"",
		"    " + commandPrefix + ` rule add "<description of the rule>"`,
		"",
		"This stores the rule in `.tddmaster/rules/` and ensures it is synced to all",
		"coding tools on the next `tddmaster sync`. Never edit `.tddmaster/rules/` directly.",
		"",
	}

	return strings.Join(lines, "\n")
}

// BuildRules generates the active rules section.
func BuildRules(rules []string) string {
	lines := []string{
		"### Active Rules",
		"",
	}

	for _, rule := range rules {
		if strings.ContainsRune(rule, '\n') {
			lines = append(lines, rule, "")
		} else {
			lines = append(lines, "- "+rule)
		}
	}

	lines = append(lines, "")

	return strings.Join(lines, "\n")
}

// BuildSection assembles the full tddmaster section.
func BuildSection(rules []string, commandPrefix string, options *statesync.SyncOptions) string {
	parts := []string{
		NosStart,
		BuildProtocol(commandPrefix, options),
		BuildCoaching(commandPrefix),
	}

	if len(rules) > 0 {
		parts = append(parts, BuildRules(rules))
	}

	parts = append(parts, NosEnd)

	return strings.Join(parts, "\n")
}

// =============================================================================
// Public API
// =============================================================================

// SyncAgentsMd generates or updates the tddmaster section in AGENTS.md.
func SyncAgentsMd(ctx statesync.SyncContext, options *statesync.SyncOptions) error {
	filePath := ctx.Root + "/" + AgentsMDFile
	section := BuildSection(ctx.Rules, ctx.CommandPrefix, options)

	var content string

	if data, err := os.ReadFile(filePath); err == nil {
		content = string(data)
		startIdx := strings.Index(content, NosStart)
		endIdx := strings.Index(content, NosEnd)

		if startIdx != -1 && endIdx != -1 {
			content = content[:startIdx] + section + content[endIdx+len(NosEnd):]
		} else {
			content = strings.TrimRight(content, "\n") + "\n\n" + section + "\n"
		}
	} else {
		content = section + "\n"
	}

	return os.WriteFile(filePath, []byte(content), 0o644)
}
